export type Icon3D = {
  name: string;
  path: string;
  tags: string[];
  category?: Category;
};

export const icons3Dpath = "/illustrations/course-icon-library/";

type Category =
  | "space-astronomy"
  | "science-technology"
  | "education-academia"
  | "nature-environment"
  | "health-medicine"
  | "food-cuisine"
  | "objects"
  | "symbols"
  | "flags"
  | "arts-entertainment"
  | "history-culture"
  | "business-finance"
  | "transport-travel"
  | "fashion-lifestyle"
  | "architecture-real-estate"
  | "programming-web"
  | "sports-games"
  | "people"
  | "miscellaneous";

export const categories = [
  "science-technology", // Includes icons related to scientific disciplines and technology
  "education-academia", // For icons associated with education and academic symbols
  "nature-environment", // Encompasses natural elements and environmental icons
  "health-medicine", // Includes health and medical-related icons
  "food-cuisine", // All icons depicting food items and culinary elements
  "objects", // General category for various objects that don't fit into other specific categories
  "symbols", // Abstract symbols, signs, and miscellaneous icons
  "flags", // Icons representing different flags
  "arts-entertainment", // Icons related to arts, entertainment, and leisure activities
  "history-culture", // For historical and cultural symbols
  "business-finance", // Icons related to business, finance, and work
  "transport-travel", // Depicting modes of transport and travel-related items
  "fashion-lifestyle", // Related to clothing, fashion, and lifestyle elements
  "architecture-real-estate", // Various buildings, architectural elements, and real estate
  "programming-web", // For programming languages, web development tools, and software
  "sports-games", // Icons related to sports, games, and other recreational activities
  "miscellaneous", // Catch-all category for icons that don't fit elsewhere
  "people", // For every illustration with people and faces to see
];

export const icons3d: Icon3D[] = [
  {
    name: "moon",
    path: icons3Dpath + "moon.webp",
    tags: ["moon", "night", "dark", "sky"],
    category: "space-astronomy",
  },
  {
    name: "atom",
    path: icons3Dpath + "atom.webp",
    tags: [
      "atom",
      "science",
      "chemistry",
      "physics",
      "molecule",
      "nucleus",
      "proton",
      "electron",
      "neutron",
    ],
    category: "nature-environment",
  },
  {
    name: "atom",
    path: icons3Dpath + "atom2.webp",
    tags: [
      "atom",
      "science",
      "chemistry",
      "physics",
      "molecule",
      "nucleus",
      "proton",
      "electron",
      "neutron",
    ],
    category: "science-technology",
  },
  {
    name: "chestplate",
    path: icons3Dpath + "chestplate.webp",
    tags: [
      "chestplate",
      "armor",
      "knight",
      "warrior",
      "medieval",
      "sword",
      "shield",
    ],
    category: "history-culture",
  },
  {
    name: "globe",
    path: icons3Dpath + "globe.webp",
    tags: [
      "globe",
      "earth",
      "planet",
      "world",
      "map",
      "global",
      "international",
    ],
    category: "nature-environment",
  },
  {
    name: "builder-hat",
    path: icons3Dpath + "builder-hat.webp",
    tags: ["builder", "hat", "construction"],
    category: "objects",
  },
  {
    name: "book",
    path: icons3Dpath + "book.webp",
    tags: [
      "book",
      "read",
      "reading",
      "literature",
      "education",
      "study",
      "knowledge",
    ],
    category: "education-academia",
  },
  {
    name: "telescope",
    path: icons3Dpath + "telescope.webp",
    tags: [
      "telescope",
      "space",
      "astronomy",
      "science",
      "universe",
      "star",
      "planet",
    ],
    category: "science-technology",
  },
  {
    name: "book-worm",
    path: icons3Dpath + "book-worm.webp",
    tags: [
      "book",
      "worm",
      "read",
      "reading",
      "literature",
      "education",
      "study",
      "knowledge",
    ],
    category: "education-academia",
  },
  {
    name: "presentation",
    path: icons3Dpath + "presentation.webp",
    tags: [
      "presentation",
      "present",
      "talk",
      "speech",
      "lecture",
      "seminar",
      "meeting",
      "conference",
    ],
    category: "education-academia",
  },
  {
    name: "cube",
    path: icons3Dpath + "cube.webp",
    tags: [
      "cube",
      "rubiks",
      "puzzle",
      "game",
      "toy",
      "box",
      "logic",
      "problem",
      "solution",
    ],
    category: "objects",
  },
  {
    name: "pride",
    path: icons3Dpath + "pride.webp",
    tags: ["pride", "rainbow", "lgbt"],
    category: "history-culture",
  },
  {
    name: "chess",
    path: icons3Dpath + "chess.webp",
    tags: [
      "chess",
      "game",
      "strategy",
      "board",
      "king",
      "queen",
      "rook",
      "bishop",
      "knight",
      "pawn",
    ],
    category: "sports-games",
  },
  {
    name: "bulb-with-leafs",
    path: icons3Dpath + "bulb-with-leafs.webp",
    tags: ["bulb", "leaf", "green", "ecology", "environment"],
    category: "nature-environment",
  },
  {
    name: "package",
    path: icons3Dpath + "package.webp",
    tags: [
      "package",
      "box",
      "gift",
      "present",
      "delivery",
      "shipping",
      "parcel",
    ],
    category: "objects",
  },
  {
    name: "dna",
    path: icons3Dpath + "dna.webp",
    tags: [
      "dna",
      "science",
      "biology",
      "chemistry",
      "molecule",
      "genetics",
      "gene",
      "cell",
    ],
    category: "science-technology",
  },
  {
    name: "microscope",
    path: icons3Dpath + "microscope.webp",
    tags: [
      "microscope",
      "science",
      "biology",
      "chemistry",
      "molecule",
      "genetics",
      "gene",
      "cell",
    ],
    category: "science-technology",
  },
  {
    name: "design",
    path: icons3Dpath + "design.webp",
    tags: [
      "design",
      "art",
      "paint",
      "brush",
      "color",
      "palette",
      "creative",
      "creativity",
      "pc",
      "computer",
      "mac",
    ],
    category: "arts-entertainment",
  },
  {
    name: "globe2",
    path: icons3Dpath + "globe2.webp",
    tags: [
      "globe",
      "earth",
      "planet",
      "world",
      "map",
      "global",
      "international",
    ],
    category: "nature-environment",
  },
  {
    name: "nuclear-facility",
    path: icons3Dpath + "nuclear-facility.webp",
    tags: [
      "nuclear",
      "facility",
      "power",
      "plant",
      "energy",
      "electricity",
      "atom",
      "science",
      "chemistry",
      "physics",
      "molecule",
      "nucleus",
      "proton",
      "electron",
      "neutron",
    ],
    category: "science-technology",
  },
  {
    name: "grinder",
    path: icons3Dpath + "grinder.webp",
    tags: ["grinder", "plants", "herbs", "grinder"],
    category: "objects",
  },
  {
    name: "brain",
    path: icons3Dpath + "brain.webp",
    tags: ["brain", "science", "biology", "chemistry", "molecule", "cell"],
    category: "science-technology",
  },
  {
    name: "rocket",
    path: icons3Dpath + "rocket.webp",
    tags: ["rocket", "space", "astronomy", "science", "universe", "star"],
    category: "science-technology",
  },
  {
    name: "packages",
    path: icons3Dpath + "packages.webp",
    tags: ["packages", "logistics", "delivery", "shipping", "parcel"],
    category: "objects",
  },
  {
    name: "flame",
    path: icons3Dpath + "flame.webp",
    tags: ["flame", "fire", "burn", "hot", "heat", "light", "energy"],
    category: "nature-environment",
  },
  {
    name: "hands-holding-together",
    path: icons3Dpath + "hands-holding-together.webp",
    tags: [
      "hands",
      "holding",
      "together",
      "team",
      "group",
      "people",
      "community",
    ],
    category: "history-culture",
  },
  {
    name: "robotic-arm",
    path: icons3Dpath + "robotic-arm.webp",
    tags: [
      "robotic",
      "arm",
      "robot",
      "machine",
      "automation",
      "industry",
      "technology",
    ],
    category: "science-technology",
  },
  {
    name: "abacus",
    path: icons3Dpath + "abacus.webp",
    tags: [
      "abacus",
      "math",
      "mathematics",
      "count",
      "counting",
      "school",
      "education",
    ],
    category: "education-academia",
  },
  {
    name: "hat-with-spy-goggles",
    path: icons3Dpath + "hat-with-spy-goggles.webp",
    tags: [
      "hat",
      "spy",
      "goggles",
      "detective",
      "investigation",
      "investigator",
      "secret",
      "agent",
    ],
    category: "miscellaneous",
  },
  {
    name: "environment",
    path: icons3Dpath + "environment.webp",
    tags: [
      "environment",
      "ecology",
      "nature",
      "green",
      "planet",
      "earth",
      "world",
    ],
    category: "nature-environment",
  },
  {
    name: "firewall",
    path: icons3Dpath + "firewall.webp",
    tags: [
      "firewall",
      "security",
      "protection",
      "network",
      "internet",
      "firewall",
    ],
    category: "science-technology",
  },
  {
    name: "flag",
    path: icons3Dpath + "flag.webp",
    tags: [
      "flag",
      "country",
      "nation",
      "state",
      "national",
      "international",
      "world",
    ],
    category: "flags",
  },
  {
    name: "church",
    path: icons3Dpath + "church.webp",
    tags: [
      "church",
      "religion",
      "christianity",
      "christian",
      "catholic",
      "catholicism",
      "religion",
    ],
    category: "history-culture",
  },
  {
    name: "cleaning-stuff",
    path: icons3Dpath + "cleaning-stuff.webp",
    tags: [
      "cleaning",
      "stuff",
      "clean",
      "hygiene",
      "household",
      "house",
      "home",
    ],
    category: "objects",
  },
  {
    name: "contract",
    path: icons3Dpath + "contract.webp",
    tags: [
      "contract",
      "law",
      "agreement",
      "sign",
      "signature",
      "document",
      "paper",
      "pen",
    ],
    category: "business-finance",
  },
  {
    name: "hammer",
    path: icons3Dpath + "hammer.webp",
    tags: ["hammer", "law", "agreement", "judge", "justice", "court", "gavel"],
    category: "objects",
  },
  {
    name: "heart",
    path: icons3Dpath + "heart.webp",
    tags: [
      "heart",
      "love",
      "medical",
      "health",
      "cardiology",
      "cardiologist",
      "doctor",
      "medicine",
    ],
    category: "health-medicine",
  },
  {
    name: "pills",
    path: icons3Dpath + "pills.webp",
    tags: [
      "pills",
      "medicine",
      "medical",
      "health",
      "pill",
      "drug",
      "drugs",
      "supplements",
    ],
    category: "health-medicine",
  },
  {
    name: "coin-bag",
    path: icons3Dpath + "coin-bag.webp",
    tags: [
      "coin",
      "bag",
      "money",
      "cash",
      "currency",
      "dollar",
      "euro",
      "pound",
      "yen",
      "dollar",
      "cent",
    ],
    category: "business-finance",
  },
  {
    name: "blueprint",
    path: icons3Dpath + "blueprint.webp",
    tags: [
      "blueprint",
      "plan",
      "architecture",
      "design",
      "draft",
      "sketch",
      "drawing",
      "project",
      "construction",
    ],
    category: "architecture-real-estate",
  },
  {
    name: "medi-pack",
    path: icons3Dpath + "medi-pack.webp",
    tags: [
      "medi",
      "pack",
      "medical",
      "health",
      "medicine",
      "first",
      "aid",
      "kit",
      "emergency",
      "supplies",
    ],
    category: "health-medicine",
  },
  {
    name: "terminal",
    path: icons3Dpath + "terminal.webp",
    tags: [
      "terminal",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
      "command",
      "line",
      "console",
      "prompt",
    ],
    category: "programming-web",
  },
  {
    name: "book-with-rose",
    path: icons3Dpath + "book-with-rose.webp",
    tags: [
      "book",
      "rose",
      "read",
      "reading",
      "literature",
      "education",
      "study",
      "knowledge",
      "romance",
      "romantic",
    ],
    category: "education-academia",
  },
  {
    name: "yingyang",
    path: icons3Dpath + "yingyang.webp",
    tags: [
      "yingyang",
      "ying",
      "yang",
      "balance",
      "harmony",
      "peace",
      "tao",
      "taoism",
      "taoist",
      "philosophy",
    ],
    category: "history-culture",
  },
  {
    name: "blueprint-2",
    path: icons3Dpath + "blueprint-2.webp",
    tags: [
      "blueprint",
      "plan",
      "architecture",
      "design",
      "draft",
      "sketch",
      "drawing",
      "project",
      "construction",
    ],
    category: "architecture-real-estate",
  },
  {
    name: "hacker",
    path: icons3Dpath + "hacker.webp",
    tags: [
      "developer",
      "hacker",
      "programmer",
      "coding",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
      "command",
      "line",
      "console",
      "prompt",
    ],
    category: "programming-web",
  },
  {
    name: "alarm",
    path: icons3Dpath + "alarm.webp",
    tags: ["alarm", "clock", "time", "wake", "up", "reminder", "alert"],
    category: "objects",
  },
  {
    name: "calendar",
    path: icons3Dpath + "calendar.webp",
    tags: [
      "calendar",
      "date",
      "time",
      "day",
      "month",
      "year",
      "schedule",
      "event",
    ],
    category: "objects",
  },
  {
    name: "carrot",
    path: icons3Dpath + "carrot.webp",
    tags: ["carrot", "food", "meal", "vegetable", "vegan", "vegetarian"],
    category: "food-cuisine",
  },
  {
    name: "christmas-tree",
    path: icons3Dpath + "christmas-tree.webp",
    tags: ["christmas", "tree", "xmas", "holiday", "winter", "snow"],
    category: "history-culture",
  },
  {
    name: "coin",
    path: icons3Dpath + "coin.webp",
    tags: [
      "coin",
      "money",
      "cash",
      "currency",
      "dollar",
      "euro",
      "pound",
      "yen",
      "dollar",
      "cent",
    ],
    category: "business-finance",
  },
  {
    name: "game",
    path: icons3Dpath + "game.webp",
    tags: ["game", "controller", "play", "videogame", "console"],
    category: "arts-entertainment",
  },
  {
    name: "garlic",
    path: icons3Dpath + "garlic.webp",
    tags: ["garlic", "food", "meal", "vegetable", "vegan", "vegetarian"],
    category: "food-cuisine",
  },
  {
    name: "gift",
    path: icons3Dpath + "gift.webp",
    tags: ["gift", "present", "box", "surprise", "birthday", "christmas"],
    category: "objects",
  },
  {
    name: "jupiter",
    path: icons3Dpath + "jupiter.webp",
    tags: ["jupiter", "planet", "space", "astronomy", "science", "universe"],
    category: "space-astronomy",
  },
  {
    name: "leek",
    path: icons3Dpath + "leek.webp",
    tags: ["leek", "food", "meal", "vegetable", "vegan", "vegetarian"],
    category: "food-cuisine",
  },
  {
    name: "map",
    path: icons3Dpath + "map.webp",
    tags: ["map", "location", "gps", "navigation", "place", "world"],
    category: "objects",
  },
  {
    name: "mars",
    path: icons3Dpath + "mars.webp",
    tags: ["mars", "planet", "space", "astronomy", "science", "universe"],
    category: "space-astronomy",
  },
  {
    name: "money-stack",
    path: icons3Dpath + "money-stack.webp",
    tags: [
      "money",
      "stack",
      "cash",
      "currency",
      "dollar",
      "euro",
      "pound",
      "yen",
      "dollar",
      "cent",
    ],
    category: "business-finance",
  },
  {
    name: "mushroom",
    path: icons3Dpath + "mushroom.webp",
    tags: ["mushroom", "food", "meal", "vegetable", "vegan", "vegetarian"],
    category: "food-cuisine",
  },
  {
    name: "pepper",
    path: icons3Dpath + "pepper.webp",
    tags: ["pepper", "food", "meal", "vegetable", "vegan", "vegetarian"],
    category: "food-cuisine",
  },
  {
    name: "snow",
    path: icons3Dpath + "snow.webp",
    tags: ["snow", "weather", "storm", "cloud", "water", "wet"],
    category: "nature-environment",
  },
  {
    name: "target",
    path: icons3Dpath + "target.webp",
    tags: ["target", "goal", "aim", "bullseye", "objective", "mission"],
    category: "objects",
  },
  {
    name: "uranus",
    path: icons3Dpath + "uranus.webp",
    tags: ["uranus", "planet", "space", "astronomy", "science", "universe"],
    category: "space-astronomy",
  },
  {
    name: "veget",
    path: icons3Dpath + "veget.webp",
    tags: ["veget", "food", "meal", "vegetable", "vegan", "vegetarian"],
    category: "food-cuisine",
  },
  {
    name: "angular",
    path: icons3Dpath + "angular.webp",
    tags: [
      "angular",
      "framework",
      "javascript",
      "js",
      "web",
      "development",
      "frontend",
      "front",
      "end",
      "framework",
      "library",
    ],
    category: "programming-web",
  },
  {
    name: "bamboo",
    path: icons3Dpath + "bamboo.webp",
    tags: ["bamboo", "food", "meal", "vegetable", "vegan", "vegetarian"],
    category: "nature-environment",
  },
  {
    name: "bank",
    path: icons3Dpath + "bank.webp",
    tags: [
      "bank",
      "money",
      "cash",
      "currency",
      "dollar",
      "euro",
      "pound",
      "yen",
    ],
    category: "business-finance",
  },
  {
    name: "barn",
    path: icons3Dpath + "barn.webp",
    tags: ["barn", "farm", "rural", "country", "house", "home"],
    category: "architecture-real-estate",
  },
  {
    name: "beach-chair",
    path: icons3Dpath + "beach-chair.webp",
    tags: ["beach", "chair", "summer", "vacation", "holiday", "relax"],
    category: "objects",
  },
  {
    name: "bezier-tool",
    path: icons3Dpath + "bezier-tool.webp",
    tags: [
      "bezier",
      "tool",
      "design",
      "art",
      "paint",
      "brush",
      "color",
      "palette",
      "creative",
      "creativity",
    ],
    category: "arts-entertainment",
  },
  {
    name: "bitcoin",
    path: icons3Dpath + "bitcoin.webp",
    tags: ["bitcoin", "crypto", "cryptocurrency", "currency", "money", "cash"],
    category: "business-finance",
  },
  {
    name: "boy-vr",
    path: icons3Dpath + "boy-vr.webp",
    tags: [
      "vr",
      "virtual reality",
      "gaming",
      "technology",
      "youth",
      "3D",
      "simulation",
      "entertainment",
      "interactive",
      "digital",
    ],
    category: "arts-entertainment",
  },
  {
    name: "bus",
    path: icons3Dpath + "bus.webp",
    tags: ["bus", "transportation", "public", "transport", "travel"],
    category: "transport-travel",
  },
  {
    name: "C-sharp",
    path: icons3Dpath + "C-sharp.webp",
    tags: [
      "c",
      "sharp",
      "csharp",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
      "command",
      "line",
      "console",
      "prompt",
    ],
    category: "programming-web",
  },
  {
    name: "C++",
    path: icons3Dpath + "C++.webp",
    tags: [
      "c",
      "c++",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
      "command",
      "line",
      "console",
      "prompt",
    ],
    category: "programming-web",
  },
  {
    name: "calendar2",
    path: icons3Dpath + "calendar2.webp",
    tags: [
      "calendar",
      "date",
      "time",
      "day",
      "month",
      "year",
      "schedule",
      "event",
    ],
    category: "objects",
  },
  {
    name: "call",
    path: icons3Dpath + "call.webp",
    tags: ["call", "phone", "telephone", "mobile", "cell", "smartphone"],
    category: "objects",
  },
  {
    name: "color-palette",
    path: icons3Dpath + "color-palette.webp",
    tags: [
      "color",
      "palette",
      "design",
      "art",
      "paint",
      "brush",
      "creative",
      "creativity",
    ],
    category: "arts-entertainment",
  },
  {
    name: "color-wheel",
    path: icons3Dpath + "color-wheel.webp",
    tags: [
      "color",
      "wheel",
      "design",
      "art",
      "paint",
      "brush",
      "creative",
      "creativity",
    ],
    category: "arts-entertainment",
  },
  {
    name: "color-wheel2",
    path: icons3Dpath + "color-wheel2.webp",
    tags: [
      "color",
      "wheel",
      "design",
      "art",
      "paint",
      "brush",
      "creative",
      "creativity",
    ],
    category: "arts-entertainment",
  },
  {
    name: "css",
    path: icons3Dpath + "css.webp",
    tags: [
      "css",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
      "command",
      "line",
      "console",
      "prompt",
    ],
    category: "programming-web",
  },
  {
    name: "dart",
    path: icons3Dpath + "dart.webp",
    tags: [
      "dart",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
      "command",
      "line",
      "console",
      "prompt",
    ],
    category: "programming-web",
  },
  {
    name: "dinosaur-fossil",
    path: icons3Dpath + "dinosaur-fossil.webp",
    tags: ["dinosaur", "fossil", "bones", "prehistoric", "ancient", "history"],
    category: "history-culture",
  },
  {
    name: "dinosaur-skull",
    path: icons3Dpath + "dinosaur-skull.webp",
    tags: ["dinosaur", "skull", "bones", "prehistoric", "ancient", "history"],
    category: "history-culture",
  },
  {
    name: "dollar-money",
    path: icons3Dpath + "dollar-money.webp",
    tags: [
      "dollar",
      "money",
      "cash",
      "currency",
      "dollar",
      "euro",
      "pound",
      "yen",
    ],
    category: "business-finance",
  },
  {
    name: "electrocardiogram",
    path: icons3Dpath + "electrocardiogram.webp",
    tags: [
      "electrocardiogram",
      "heart",
      "medical",
      "health",
      "cardiology",
      "cardiologist",
      "doctor",
      "medicine",
    ],
    category: "health-medicine",
  },
  {
    name: "facebook",
    path: icons3Dpath + "facebook.webp",
    tags: [
      "facebook",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "faces",
    path: icons3Dpath + "faces.webp",
    tags: ["faces", "people", "community", "group", "team", "together"],
    category: "history-culture",
  },
  {
    name: "flail",
    path: icons3Dpath + "flail.webp",
    tags: ["flail", "weapon", "medieval", "war", "battle", "fight"],
    category: "history-culture",
  },
  {
    name: "flutter",
    path: icons3Dpath + "flutter.webp",
    tags: [
      "flutter",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
      "command",
      "line",
      "console",
      "prompt",
    ],
    category: "programming-web",
  },
  {
    name: "followers",
    path: icons3Dpath + "followers.webp",
    tags: ["followers", "social", "media", "network", "internet", "online"],
    category: "miscellaneous",
  },
  {
    name: "git",
    path: icons3Dpath + "git.webp",
    tags: [
      "git",
      "version",
      "control",
      "system",
      "vcs",
      "software",
      "development",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
      "command",
      "line",
      "console",
      "prompt",
      "github",
    ],
    category: "programming-web",
  },
  {
    name: "go",
    path: icons3Dpath + "go.webp",
    tags: [
      "go",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "goal",
    path: icons3Dpath + "goal.webp",
    tags: ["goal", "target", "aim", "bullseye", "objective", "mission"],
    category: "objects",
  },
  {
    name: "gpu",
    path: icons3Dpath + "gpu.webp",
    tags: [
      "gpu",
      "graphics",
      "processing",
      "unit",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "science-technology",
  },
  {
    name: "greenhouse",
    path: icons3Dpath + "greenhouse.webp",
    tags: ["greenhouse", "plants", "herbs", "grinder"],
    category: "objects",
  },
  {
    name: "handcuff",
    path: icons3Dpath + "handcuff.webp",
    tags: ["handcuff", "police", "arrest", "law", "justice", "handcuffs"],
    category: "objects",
  },
  {
    name: "headphone",
    path: icons3Dpath + "headphone.webp",
    tags: ["headphone", "music", "audio", "sound", "listen", "earphone"],
    category: "objects",
  },
  {
    name: "hospital",
    path: icons3Dpath + "hospital.webp",
    tags: ["hospital", "medical", "health", "clinic", "doctor", "medicine"],
    category: "health-medicine",
  },
  {
    name: "hotel",
    path: icons3Dpath + "hotel.webp",
    tags: ["hotel", "travel", "vacation", "holiday", "motel", "inn"],
    category: "architecture-real-estate",
  },
  {
    name: "house",
    path: icons3Dpath + "house.webp",
    tags: ["house", "home", "building", "residence", "residential"],
    category: "architecture-real-estate",
  },
  {
    name: "html",
    path: icons3Dpath + "html.webp",
    tags: [
      "html",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "igloo",
    path: icons3Dpath + "igloo.webp",
    tags: ["igloo", "ice", "snow", "winter", "cold", "house", "home"],
    category: "architecture-real-estate",
  },
  {
    name: "java",
    path: icons3Dpath + "java.webp",
    tags: [
      "java",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "js",
    path: icons3Dpath + "js.webp",
    tags: [
      "js",
      "javascript",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "justice-scale",
    path: icons3Dpath + "justice-scale.webp",
    tags: ["justice", "scale", "law", "judge", "court", "gavel"],
    category: "objects",
  },
  {
    name: "keyboard",
    path: icons3Dpath + "keyboard.webp",
    tags: ["keyboard", "computer", "pc", "mac", "linux", "unix"],
    category: "objects",
  },
  {
    name: "kotlin",
    path: icons3Dpath + "kotlin.webp",
    tags: [
      "kotlin",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "layers",
    path: icons3Dpath + "layers.webp",
    tags: [
      "layers",
      "design",
      "art",
      "paint",
      "brush",
      "creative",
      "creativity",
    ],
    category: "arts-entertainment",
  },
  {
    name: "linkedin",
    path: icons3Dpath + "linkedIn.webp",
    tags: [
      "linkedin",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "luxury-house",
    path: icons3Dpath + "luxury-house.webp",
    tags: ["luxury", "house", "home", "building", "residence", "residential"],
    category: "architecture-real-estate",
  },
  {
    name: "magic",
    path: icons3Dpath + "magic.webp",
    tags: ["magic", "wand", "witch", "wizard", "spell", "cast"],
    category: "miscellaneous",
  },
  {
    name: "mail",
    path: icons3Dpath + "mail.webp",
    tags: ["mail", "email", "message", "envelope", "letter", "post"],
    category: "objects",
  },
  {
    name: "map-compass",
    path: icons3Dpath + "map-compass.webp",
    tags: ["map", "compass", "location", "gps", "navigation", "place", "world"],
    category: "objects",
  },
  {
    name: "moai-stone",
    path: icons3Dpath + "moai-stone.webp",
    tags: ["moai", "stone", "easter", "island", "statue", "ancient", "history"],
    category: "history-culture",
  },
  {
    name: "molecule-structure",
    path: icons3Dpath + "molecule-structure.webp",
    tags: [
      "molecule",
      "structure",
      "science",
      "chemistry",
      "physics",
      "nucleus",
      "proton",
      "electron",
      "neutron",
    ],
    category: "science-technology",
  },
  {
    name: "mongodb",
    path: icons3Dpath + "mongodb.webp",
    tags: [
      "mongodb",
      "database",
      "storage",
      "data",
      "software",
      "development",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "monster",
    path: icons3Dpath + "monster.webp",
    tags: ["monster", "creature", "animal", "beast", "myth", "legend"],
    category: "nature-environment",
  },
  {
    name: "nodejs",
    path: icons3Dpath + "nodejs.webp",
    tags: [
      "nodejs",
      "node",
      "js",
      "javascript",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "octopus",
    path: icons3Dpath + "octopus.webp",
    tags: ["octopus", "animal", "sea", "ocean", "tentacles"],
    category: "nature-environment",
  },
  {
    name: "office",
    path: icons3Dpath + "office.webp",
    tags: ["office", "work", "desk", "job", "business", "workplace"],
    category: "architecture-real-estate",
  },
  {
    name: "php",
    path: icons3Dpath + "php.webp",
    tags: [
      "php",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "pickup-car",
    path: icons3Dpath + "pickup-car.webp",
    tags: ["pickup", "car", "vehicle", "transportation", "transport"],
    category: "transport-travel",
  },
  {
    name: "pills2",
    path: icons3Dpath + "pills2.webp",
    tags: [
      "pills",
      "medicine",
      "medical",
      "health",
      "pill",
      "drug",
      "drugs",
      "supplements",
    ],
    category: "health-medicine",
  },
  {
    name: "playing-Cards",
    path: icons3Dpath + "playing-Cards.webp",
    tags: ["playing", "cards", "game", "poker", "casino", "gambling"],
    category: "arts-entertainment",
  },
  {
    name: "police-car",
    path: icons3Dpath + "police-car.webp",
    tags: ["police", "car", "vehicle", "transportation", "transport"],
    category: "transport-travel",
  },
  {
    name: "puzzle",
    path: icons3Dpath + "puzzle.webp",
    tags: ["puzzle", "game", "challenge", "problem", "solution", "piece"],
    category: "arts-entertainment",
  },
  {
    name: "ram",
    path: icons3Dpath + "ram.webp",
    tags: [
      "ram",
      "random",
      "access",
      "memory",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "science-technology",
  },
  {
    name: "raspberrypie",
    path: icons3Dpath + "raspberry.webp",
    tags: [
      "raspberry",
      "pie",
      "raspberry pie",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "react",
    path: icons3Dpath + "react.webp",
    tags: [
      "react",
      "framework",
      "javascript",
      "js",
      "web",
      "development",
      "frontend",
      "front",
      "end",
      "framework",
      "library",
    ],
    category: "programming-web",
  },
  {
    name: "recycle",
    path: icons3Dpath + "recycle.webp",
    tags: ["recycle", "environment", "ecology", "nature", "green"],
    category: "nature-environment",
  },
  {
    name: "rust",
    path: icons3Dpath + "rust.webp",
    tags: [
      "rust",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "school",
    path: icons3Dpath + "school.webp",
    tags: ["school", "education", "study", "learning", "student", "teacher"],
    category: "education-academia",
  },
  {
    name: "setting",
    path: icons3Dpath + "setting.webp",
    tags: ["setting", "gear", "options", "preferences", "config", "configure"],
    category: "objects",
  },
  {
    name: "shop",
    path: icons3Dpath + "shop.webp",
    tags: ["shop", "store", "mall", "market", "buy", "sell", "commerce"],
    category: "architecture-real-estate",
  },
  {
    name: "spartan",
    path: icons3Dpath + "spartan.webp",
    tags: ["spartan", "warrior", "helmet", "armor", "battle", "fight"],
    category: "history-culture",
  },
  {
    name: "suitcase",
    path: icons3Dpath + "suitcase.webp",
    tags: ["suitcase", "travel", "bag", "luggage", "baggage", "case"],
    category: "transport-travel",
  },
  {
    name: "suv",
    path: icons3Dpath + "suv.webp",
    tags: ["suv", "car", "vehicle", "transportation", "transport"],
    category: "transport-travel",
  },
  {
    name: "swift",
    path: icons3Dpath + "swift.webp",
    tags: [
      "swift",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "tank",
    path: icons3Dpath + "tank.webp",
    tags: ["tank", "war", "battle", "fight", "military", "army"],
    category: "history-culture",
  },
  {
    name: "taxi",
    path: icons3Dpath + "taxi.webp",
    tags: ["taxi", "car", "vehicle", "transportation", "transport"],
    category: "transport-travel",
  },
  {
    name: "theme-park",
    path: icons3Dpath + "theme-park.webp",
    tags: ["theme", "park", "amusement", "fun", "roller", "coaster"],
    category: "arts-entertainment",
  },
  {
    name: "tiny-house",
    path: icons3Dpath + "tiny-house.webp",
    tags: ["tiny", "house", "home", "building", "residence", "residential"],
    category: "architecture-real-estate",
  },
  {
    name: "translator",
    path: icons3Dpath + "translator.webp",
    tags: ["translator", "language", "translate", "interpret"],
    category: "history-culture",
  },
  {
    name: "ts",
    path: icons3Dpath + "ts.webp",
    tags: [
      "ts",
      "typescript",
      "language",
      "programming",
      "code",
      "computer",
      "pc",
      "mac",
      "linux",
      "unix",
    ],
    category: "programming-web",
  },
  {
    name: "ufo",
    path: icons3Dpath + "ufo.webp",
    tags: ["ufo", "alien", "space", "astronomy", "science", "universe"],
    category: "nature-environment",
  },
  {
    name: "viking-ship",
    path: icons3Dpath + "viking-ship.webp",
    tags: ["viking", "ship", "boat", "sea", "ocean", "sail"],
    category: "history-culture",
  },
  {
    name: "atom",
    path: icons3Dpath + "virtual-world.webp",
    tags: ["atom", "science", "chemistry", "physics", "nucleus", "proton"],
    category: "science-technology",
  },
  {
    name: "virus",
    path: icons3Dpath + "virus.webp",
    tags: ["virus", "bacteria", "disease", "sickness", "illness", "health"],
    category: "health-medicine",
  },
  {
    name: "virus2",
    path: icons3Dpath + "virus2.webp",
    tags: ["virus", "bacteria", "disease", "sickness", "illness", "health"],
    category: "health-medicine",
  },
  {
    name: "vr-glasses",
    path: icons3Dpath + "vr-glasses.webp",
    tags: [
      "vr",
      "virtual reality",
      "gaming",
      "technology",
      "3D",
      "simulation",
      "entertainment",
      "interactive",
      "digital",
    ],
    category: "arts-entertainment",
  },
  {
    name: "wheelchair",
    path: icons3Dpath + "wheelchair.webp",
    tags: ["wheelchair", "disabled", "handicap", "accessibility"],
    category: "miscellaneous",
  },
  {
    name: "wordpress",
    path: icons3Dpath + "wordpress.webp",
    tags: [
      "wordpress",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "programming-web",
  },
  {
    name: "xray",
    path: icons3Dpath + "xray.webp",
    tags: [
      "xray",
      "medical",
      "health",
      "medicine",
      "doctor",
      "hospital",
      "clinic",
    ],
    category: "health-medicine",
  },
  {
    name: "american-football",
    path: icons3Dpath + "american-football.webp",
    tags: ["american", "football", "sport", "game", "ball", "nfl"],
    category: "sports-games",
  },
  {
    name: "archery",
    path: icons3Dpath + "archery.webp",
    tags: ["archery", "sport", "game", "bow", "arrow", "target", "aim"],
    category: "sports-games",
  },
  {
    name: "baseball",
    path: icons3Dpath + "baseball.webp",
    tags: ["baseball", "sport", "game", "ball", "mlb"],
    category: "sports-games",
  },
  {
    name: "basketball",
    path: icons3Dpath + "basketball.webp",
    tags: ["basketball", "sport", "game", "ball", "nba"],
    category: "sports-games",
  },
  {
    name: "chess2",
    path: icons3Dpath + "chess2.webp",
    tags: ["chess", "sport", "game", "board", "king", "queen", "pawn"],
    category: "sports-games",
  },
  {
    name: "football",
    path: icons3Dpath + "football.webp",
    tags: ["football", "sport", "game", "ball", "soccer", "fifa"],
    category: "sports-games",
  },
  {
    name: "games",
    path: icons3Dpath + "games.webp",
    tags: ["games", "sport", "game", "ball", "soccer", "fifa"],
    category: "sports-games",
  },
  {
    name: "racing",
    path: icons3Dpath + "racing.webp",
    tags: ["racing", "sport", "game", "ball", "soccer", "fifa"],
    category: "sports-games",
  },
  {
    name: "cloud-rainbow",
    path: icons3Dpath + "cloud-rainbow.webp",
    tags: ["cloud", "rainbow", "weather", "storm", "cloud", "water", "wet"],
    category: "nature-environment",
  },
  {
    name: "cloud-stars",
    path: icons3Dpath + "cloud-stars.webp",
    tags: ["cloud", "stars", "weather", "storm", "cloud", "water", "wet"],
    category: "nature-environment",
  },
  {
    name: "cloudy-day",
    path: icons3Dpath + "cloudy-day.webp",
    tags: ["cloudy", "day", "weather", "storm", "cloud", "water", "wet"],
    category: "nature-environment",
  },
  {
    name: "cloudy-thunder",
    path: icons3Dpath + "cloudy-thunder.webp",
    tags: ["cloudy", "thunder", "weather", "storm", "cloud", "water", "wet"],
    category: "nature-environment",
  },
  {
    name: "cloudy",
    path: icons3Dpath + "cloudy.webp",
    tags: ["cloudy", "weather", "storm", "cloud", "water", "wet", "night"],
    category: "nature-environment",
  },
  {
    name: "drizzle",
    path: icons3Dpath + "drizzle.webp",
    tags: ["drizzle", "weather", "storm", "cloud", "water", "wet"],
    category: "nature-environment",
  },
  {
    name: "heavy-rain",
    path: icons3Dpath + "heavy-rain.webp",
    tags: ["heavy", "rain", "weather", "storm", "cloud", "water", "wet"],
    category: "nature-environment",
  },
  {
    name: "snow-tornado",
    path: icons3Dpath + "snow-tornado.webp",
    tags: ["snow", "tornado", "weather", "storm", "cloud", "water", "wet"],
    category: "nature-environment",
  },
  {
    name: "snowfall",
    path: icons3Dpath + "snowfall.webp",
    tags: ["snowfall", "weather", "storm", "cloud", "water", "wet"],
    category: "nature-environment",
  },
  {
    name: "data-breach",
    path: icons3Dpath + "data-breach.webp",
    tags: ["data", "breach", "security", "hacker", "hack", "attack"],
    category: "science-technology",
  },
  {
    name: "trojan-horse",
    path: icons3Dpath + "trojan-horse.webp",
    tags: ["trojan", "horse", "security", "hacker", "hack", "attack"],
    category: "science-technology",
  },
  {
    name: "gold-bar",
    path: icons3Dpath + "gold-bar.webp",
    tags: [
      "gold",
      "bar",
      "money",
      "cash",
      "currency",
      "dollar",
      "euro",
      "pound",
      "yen",
    ],
    category: "business-finance",
  },
  {
    name: "credit-card",
    path: icons3Dpath + "credit-card.webp",
    tags: ["credit", "card", "money", "cash", "currency", "dollar"],
    category: "business-finance",
  },
  {
    name: "gold",
    path: icons3Dpath + "gold.webp",
    tags: [
      "gold",
      "money",
      "cash",
      "currency",
      "dollar",
      "euro",
      "pound",
      "yen",
    ],
    category: "business-finance",
  },
  {
    name: "money-plant",
    path: icons3Dpath + "money-plant.webp",
    tags: [
      "money",
      "plant",
      "cash",
      "currency",
      "dollar",
      "euro",
      "pound",
      "yen",
    ],
    category: "business-finance",
  },
  {
    name: "piggy-bank",
    path: icons3Dpath + "piggy-bank.webp",
    tags: ["piggy", "bank", "money", "cash", "currency", "dollar"],
    category: "business-finance",
  },
  {
    name: "acoustic-guitar",
    path: icons3Dpath + "acoustic-guitar.webp",
    tags: ["acoustic", "guitar", "music", "audio", "sound", "listen"],
    category: "arts-entertainment",
  },
  {
    name: "bass-guitar",
    path: icons3Dpath + "bass-guitar.webp",
    tags: ["bass", "guitar", "music", "audio", "sound", "listen"],
    category: "arts-entertainment",
  },
  {
    name: "cello",
    path: icons3Dpath + "cello.webp",
    tags: ["cello", "music", "audio", "sound", "listen"],
    category: "arts-entertainment",
  },
  {
    name: "electric-guitar",
    path: icons3Dpath + "electric-guitar.webp",
    tags: ["electric", "guitar", "music", "audio", "sound", "listen"],
    category: "arts-entertainment",
  },
  {
    name: "free-accordion",
    path: icons3Dpath + "free-accordion.webp",
    tags: ["free", "accordion", "music", "audio", "sound", "listen"],
    category: "arts-entertainment",
  },
  {
    name: "harmon",
    path: icons3Dpath + "harmon.webp",
    tags: ["harmon", "music", "audio", "sound", "listen"],
    category: "arts-entertainment",
  },
  {
    name: "snare-drum",
    path: icons3Dpath + "snare-drum.webp",
    tags: ["snare", "drum", "music", "audio", "sound", "listen"],
    category: "arts-entertainment",
  },
  {
    name: "astrounaut-helmet",
    path: icons3Dpath + "astronaut-helmet.webp",
    tags: ["astrounaut", "helmet", "space", "astronomy", "science", "universe"],
    category: "space-astronomy",
  },
  {
    name: "black-hole",
    path: icons3Dpath + "black-hole.webp",
    tags: ["black", "hole", "space", "astronomy", "science", "universe"],
    category: "space-astronomy",
  },

  {
    name: "comet",
    path: icons3Dpath + "comet.webp",
    tags: ["comet", "space", "astronomy", "science", "universe"],
    category: "space-astronomy",
  },

  {
    name: "earth2",
    path: icons3Dpath + "earth2.webp",
    tags: ["earth", "space", "astronomy", "science", "universe"],
    category: "space-astronomy",
  },

  {
    name: "mars2",
    path: icons3Dpath + "mars2.webp",
    tags: ["mars", "space", "astronomy", "science", "universe"],
    category: "space-astronomy",
  },
  {
    name: "stars",
    path: icons3Dpath + "stars.webp",
    tags: ["stars", "space", "astronomy", "science", "universe"],
    category: "space-astronomy",
  },
  {
    name: "airplane",
    path: icons3Dpath + "airplane.webp",
    tags: ["airplane", "travel", "transportation", "transport", "flight"],
    category: "transport-travel",
  },
  {
    name: "bicycle",
    path: icons3Dpath + "bicycle.webp",
    tags: ["bicycle", "travel", "transportation", "transport", "bike"],
    category: "transport-travel",
  },
  {
    name: "boat",
    path: icons3Dpath + "boat.webp",
    tags: ["boat", "travel", "transportation", "transport", "ship"],
    category: "transport-travel",
  },
  {
    name: "motorcycle",
    path: icons3Dpath + "motorcycle.webp",
    tags: ["motorcycle", "travel", "transportation", "transport", "bike"],
    category: "transport-travel",
  },
  {
    name: "behance",
    path: icons3Dpath + "behance.webp",
    tags: [
      "behance",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "dribbble",
    path: icons3Dpath + "dribbble.webp",
    tags: [
      "dribbble",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "facebook-messenger",
    path: icons3Dpath + "facebook-messenger.webp",
    tags: [
      "facebook",
      "messenger",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "flickr",
    path: icons3Dpath + "flickr.webp",
    tags: [
      "flickr",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "github",
    path: icons3Dpath + "github.webp",
    tags: [
      "github",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "google-plus",
    path: icons3Dpath + "google-plus.webp",
    tags: [
      "google",
      "plus",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "instagram",
    path: icons3Dpath + "instagram.webp",
    tags: [
      "instagram",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "piterest",
    path: icons3Dpath + "piterest.webp",
    tags: [
      "piterest",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "reddit",
    path: icons3Dpath + "reddit.webp",
    tags: [
      "reddit",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "skype",
    path: icons3Dpath + "skype.webp",
    tags: [
      "skype",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "snapchat",
    path: icons3Dpath + "snapchat.webp",
    tags: [
      "snapchat",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "spotify",
    path: icons3Dpath + "spotify.webp",
    tags: [
      "spotify",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "telegram",
    path: icons3Dpath + "telegram.webp",
    tags: [
      "telegram",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "tiktok",
    path: icons3Dpath + "tiktok.webp",
    tags: [
      "tiktok",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "tumblr",
    path: icons3Dpath + "tumblr.webp",
    tags: [
      "tumblr",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "twitch",
    path: icons3Dpath + "twitch.webp",
    tags: [
      "twitch",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "vimeo",
    path: icons3Dpath + "vimeo.webp",
    tags: [
      "vimeo",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "whatsapp",
    path: icons3Dpath + "whatsapp.webp",
    tags: [
      "whatsapp",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "youtube",
    path: icons3Dpath + "youtube.webp",
    tags: [
      "youtube",
      "social",
      "media",
      "network",
      "internet",
      "online",
      "website",
    ],
    category: "symbols",
  },
  {
    name: "banh-xeo",
    path: icons3Dpath + "banh-xeo.webp",
    tags: ["banh", "xeo", "food", "vietnam", "vietnamese", "asian"],
    category: "food-cuisine",
  },
  {
    name: "boba-drink",
    path: icons3Dpath + "boba-drink.webp",
    tags: ["boba", "drink", "food", "vietnam", "vietnamese", "asian"],
    category: "food-cuisine",
  },
  {
    name: "burger",
    path: icons3Dpath + "burger.webp",
    tags: ["burger", "food", "fast food", "grill", "cheesy"],
    category: "food-cuisine",
  },
  {
    name: "cheese",
    path: icons3Dpath + "cheese.webp",
    tags: ["cheese", "food", "dairy", "gouda", "melted"],
    category: "food-cuisine",
  },
  {
    name: "chocolate-bar",
    path: icons3Dpath + "chocolate-bar.webp",
    tags: ["chocolate", "bar", "food", "sweet", "snack", "sugar"],
    category: "food-cuisine",
  },
  {
    name: "cookie",
    path: icons3Dpath + "cookie.webp",
    tags: ["cookie", "food", "sweet", "sugar", "snack", "crispy"],
    category: "food-cuisine",
  },
  {
    name: "cupcake",
    path: icons3Dpath + "cupcake.webp",
    tags: ["cupcake", "food", "homemade", "sugar", "snack", "desert", "sweet"],
    category: "food-cuisine",
  },
  {
    name: "doughnut",
    path: icons3Dpath + "doughnut.webp",
    tags: ["doughnut", "food", "sugar", "snack", "desert", "sweet"],
    category: "food-cuisine",
  },
  {
    name: "fish-noodle-soup",
    path: icons3Dpath + "fish-noodle-soup.webp",
    tags: ["fish", "noodle", "soup", "food", "vietnam", "vietnamese", "asian"],
    category: "food-cuisine",
  },
  {
    name: "french-fries",
    path: icons3Dpath + "french-fries.webp",
    tags: ["french", "fries", "food", "potato", "fried", "crispy"],
    category: "food-cuisine",
  },
  {
    name: "fried-chicken",
    path: icons3Dpath + "fried-chicken.webp",
    tags: ["fried", "chicken", "food", "meat", "fast food", "meal"],
    category: "food-cuisine",
  },
  {
    name: "ice-cream-stick",
    path: icons3Dpath + "ice-cream-stick.webp",
    tags: ["ice", "cream", "stick", "food", "desert", "summer", "snack"],
    category: "food-cuisine",
  },
  {
    name: "soda-can",
    path: icons3Dpath + "soda-can.webp",
    tags: ["soda", "can", "drink", "food", "refreshing", "carbonated"],
    category: "food-cuisine",
  },

  //// NEW !!!
  {
    name: "beach-chair2",
    path: icons3Dpath + "beach-chair2.webp",
    tags: ["beach nchair", "beach", "chair", "summer", "sea", "sun"],
    category: "objects",
  },
  {
    name: "ai-learning",
    path: icons3Dpath + "ai-learning.webp",
    tags: [
      "ai learning",
      "ai",
      "learning",
      "technology",
      "artificial intelegence",
      "future",
    ],
    category: "science-technology",
  },
  {
    name: "air-ballon",
    path: icons3Dpath + "air-ballon.webp",
    tags: ["air ballon", "air", "ballon", "sky", "adventure"],
    category: "transport-travel",
  },
  {
    name: "airline-ticket",
    path: icons3Dpath + "airline-ticket.webp",
    tags: ["airline ticket", "airline", "ticket", "air", "airport", "flight"],
    category: "transport-travel",
  },
  {
    name: "airport-building",
    path: icons3Dpath + "airport-building.webp",
    tags: [
      "airport building",
      "airport",
      "building",
      "flights",
      "terminal",
      "gateway",
    ],
    category: "architecture-real-estate",
  },
  {
    name: "apple-juice",
    path: icons3Dpath + "apple-juice.webp",
    tags: ["apple", "juice", "apple juice", "fruits", "healthy"],
    category: "food-cuisine",
  },
  {
    name: "archery2",
    path: icons3Dpath + "archery2.webp",
    tags: ["archery", "arrow", "sport", "bow", "target"],
    category: "sports-games",
  },
  {
    name: "aroma-therapy",
    path: icons3Dpath + "aroma-therapy.webp",
    tags: ["arome", "therapy", "scent", "good smell", "relaxation"],
    category: "objects",
  },
  {
    name: "avocado-nigiri",
    path: icons3Dpath + "avocado-nigiri.webp",
    tags: [
      "avocado",
      "nigiri",
      "avocado nigiri",
      "japanese",
      "japanese food",
      "food",
    ],
    category: "food-cuisine",
  },
  {
    name: "avocado",
    path: icons3Dpath + "avocado.webp",
    tags: ["avocado", "fruit", "food", "healthy", "healthy food", "oils"],
    category: "food-cuisine",
  },
  {
    name: "ball-badminton",
    path: icons3Dpath + "ball-badminton.webp",
    tags: [
      "ball badminton",
      "ball",
      "badminton",
      "sports",
      "activity",
      "championship",
    ],
    category: "sports-games",
  },
  {
    name: "barbell",
    path: icons3Dpath + "barbell.webp",
    tags: ["barbell", "weights", "gym", "strength", "strong", "metal", "heavy"],
    category: "sports-games",
  },
  {
    name: "battery",
    path: icons3Dpath + "battery.webp",
    tags: ["battery", "charging", "power", "energy", "voltage"],
    category: "miscellaneous",
  },
  {
    name: "bedouin-tent",
    path: icons3Dpath + "bedouin-tent.webp",
    tags: ["bedouin tent", "bedouin", "tent", "nomadic", "camp", "traditional"],
    category: "history-culture",
  },
  {
    name: "beer-vat",
    path: icons3Dpath + "beer-vat.webp",
    tags: ["beer-vat", "beer", "vat", "brewery", "tank"],
    category: "objects",
  },
  {
    name: "billiard",
    path: icons3Dpath + "billiard.webp",
    tags: ["billiard", "game", "activity", "cue", "balls", "chalk"],
    category: "sports-games",
  },
  {
    name: "bowling-pin",
    path: icons3Dpath + "bowling-pin.webp",
    tags: [
      "bowling pin",
      "bowling",
      "pin",
      "sports",
      "activity",
      "fun game",
      "game",
    ],
    category: "sports-games",
  },
  {
    name: "boxing",
    path: icons3Dpath + "boxing.webp",
    tags: ["boxing", "championship", "strength", "fight", "ring", "punch"],
    category: "sports-games",
  },
  {
    name: "bright-and-a-little-thunder",
    path: icons3Dpath + "bright-and-a-little-thunder.webp",
    tags: ["bright", "thunder", "sun", "sky", "weather", "cloud"],
    category: "nature-environment",
  },
  {
    name: "browser-chart",
    path: icons3Dpath + "browser-chart.webp",
    tags: [
      "browser chart",
      "browser",
      "chart",
      "graphic",
      "statistic",
      "measurment",
    ],
    category: "objects",
  },
  {
    name: "btc",
    path: icons3Dpath + "btc.webp",
    tags: ["btc", "finance", "bitcoin", "investment", "profit", "money"],
    category: "business-finance",
  },
  {
    name: "candle-cake",
    path: icons3Dpath + "candle-cake.webp",
    tags: ["candle cake", "candle", "cake", "birthday", "party", "food"],
    category: "food-cuisine",
  },
  {
    name: "candles",
    path: icons3Dpath + "candles.webp",
    tags: ["candles", "light", "bright", "smell", "warmth", "christmas"],
    category: "objects",
  },
  {
    name: "candles2",
    path: icons3Dpath + "candles2.webp",
    tags: ["candles", "light", "bright", "smell", "warmth", "christmas"],
    category: "objects",
  },
  {
    name: "chatbot",
    path: icons3Dpath + "chatbot.webp",
    tags: ["chatbot", "ai", "technology", "smart", "service", "support"],
    category: "science-technology",
  },
  {
    name: "chinese-gate",
    path: icons3Dpath + "chinese-gate.webp",
    tags: ["chinese gate", "chinese", "gate", "culture", "traditional", "arch"],
    category: "architecture-real-estate",
  },
  {
    name: "chinese-lantern",
    path: icons3Dpath + "chinese-lantern.webp",
    tags: [
      "chinese lantern",
      "chinese-",
      "antern",
      "culture",
      "traditional",
      "arch",
    ],
    category: "history-culture",
  },
  {
    name: "chocolate-wafer",
    path: icons3Dpath + "chocolate-wafer.webp",
    tags: ["chocolate wafer", "chocolate", "wafer", "food", "sweets"],
    category: "food-cuisine",
  },
  {
    name: "christmas-snowman",
    path: icons3Dpath + "christmas-snowman.webp",
    tags: ["christmas snowman", "christmas", "snowman", "snow", "cold"],
    category: "miscellaneous",
  },
  {
    name: "clapperboard",
    path: icons3Dpath + "clapperboard.webp",
    tags: [
      "clapperboard",
      "board",
      "film",
      "movie",
      "start",
      "record",
      "action",
    ],
    category: "arts-entertainment",
  },
  {
    name: "cloudy-sky",
    path: icons3Dpath + "cloudy-sky.webp",
    tags: ["cloudy sky", "cloudy", "sky", "white", "weather"],
    category: "nature-environment",
  },
  {
    name: "cloudy-snow-wind-at-night",
    path: icons3Dpath + "cloudy-snow-wind-at-night.webp",
    tags: ["cloudy", "snow", "wind", "night", "weather", "sky"],
    category: "nature-environment",
  },
  {
    name: "cloudy-snowy-and-lightning",
    path: icons3Dpath + "cloudy-snowy-and-lightning.webp",
    tags: ["cloudy", "snow", "wind", "thunder", "weather", "sky"],
    category: "nature-environment",
  },
  {
    name: "coffee-beans",
    path: icons3Dpath + "coffee-beans.webp",
    tags: ["coffee beans", "coffee", "beans", "drink"],
    category: "food-cuisine",
  },
  {
    name: "coffee-mug",
    path: icons3Dpath + "coffee-mug.webp",
    tags: ["coffee mug", "coffee", "mug", "drink"],
    category: "food-cuisine",
  },
  {
    name: "cold-temperature",
    path: icons3Dpath + "cold-temperature.webp",
    tags: ["cold temperature", "cold", "temperature", "weather", "ice"],
    category: "nature-environment",
  },
  {
    name: "cucumber-slices",
    path: icons3Dpath + "cucumber-slices.webp",
    tags: [
      "cucumber slices",
      "cucumber",
      "slices",
      "vegetable",
      "food",
      "healthy",
      "spa",
    ],
    category: "food-cuisine",
  },
  {
    name: "dice",
    path: icons3Dpath + "dice.webp",
    tags: ["dice", "game", "numbers", "chance", "roll", "luck"],
    category: "sports-games",
  },
  {
    name: "dragon-fruit",
    path: icons3Dpath + "dragon-fruit.webp",
    tags: ["dragon fruit", "dragon", "fruit", "healthy", "food"],
    category: "food-cuisine",
  },
  {
    name: "fire-place",
    path: icons3Dpath + "fire-place.webp",
    tags: ["fire place", "fire", "place", "winter", "warmth", "kamin"],
    category: "miscellaneous",
  },
  {
    name: "fitness-mat",
    path: icons3Dpath + "fitness-mat.webp",
    tags: ["fitness mat", "fitness", "mat", "gym", "yoga", "health", "pilates"],
    category: "sports-games",
  },
  {
    name: "flower-bouquet",
    path: icons3Dpath + "flower-bouquet.webp",
    tags: ["flower bouqet", "flower", "bouqet", "romantic", "roses", "love"],
    category: "nature-environment",
  },
  {
    name: "flower-bouquet2",
    path: icons3Dpath + "flower-bouquet2.webp",
    tags: ["flower bouqet", "flower", "bouqet", "romantic", "roses", "love"],
    category: "nature-environment",
  },
  {
    name: "flute",
    path: icons3Dpath + "flute.webp",
    tags: ["flute", "sound", "music", "instrument", "breath"],
    category: "arts-entertainment",
  },
  {
    name: "football2",
    path: icons3Dpath + "football2.webp",
    tags: ["football", "game", "sport", "ball", "foot"],
    category: "sports-games",
  },
  {
    name: "go-game-board",
    path: icons3Dpath + "go-game-board.webp",
    tags: [
      "go game board",
      "game board",
      "game",
      "board",
      "fun",
      "win",
      "play",
    ],
    category: "sports-games",
  },
  {
    name: "golf",
    path: icons3Dpath + "golf.webp",
    tags: ["golf", "game", "sports", "activity", "play", "ball"],
    category: "sports-games",
  },
  {
    name: "graduation-certificate",
    path: icons3Dpath + "graduation-certificate.webp",
    tags: [
      "graduation certificate",
      "graduation",
      "certificate",
      "college",
      "award",
    ],
    category: "education-academia",
  },
  {
    name: "green-grape",
    path: icons3Dpath + "green-grape.webp",
    tags: ["green grapes", "green", "grapes", "fruit", "food"],
    category: "food-cuisine",
  },
  {
    name: "green-tea",
    path: icons3Dpath + "green-tea.webp",
    tags: ["green tea", "green", "tea", "healthy", "drink"],
    category: "food-cuisine",
  },
  {
    name: "halloween-ball",
    path: icons3Dpath + "halloween-ball.webp",
    tags: ["halloween ball", "halloween", "ball", "sceary", "mystery"],
    category: "objects",
  },
  {
    name: "map-book",
    path: icons3Dpath + "map-book.webp",
    tags: ["map book", "map", "book", "geography", "goe", "world"],
    category: "education-academia",
  },
  {
    name: "martian-habitat",
    path: icons3Dpath + "martian-habitat.webp",
    tags: [
      "martian habitat",
      "martian",
      "habitat",
      "space",
      "colony",
      "astronauts",
    ],
    category: "space-astronomy",
  },
  {
    name: "match-box",
    path: icons3Dpath + "match-box.webp",
    tags: ["match box", "match", "box", "fire"],
    category: "objects",
  },
  {
    name: "moon2",
    path: icons3Dpath + "moon2.webp",
    tags: ["mooon", "sky", "shining", "half moon"],
    category: "nature-environment",
  },
  {
    name: "no-mail-found",
    path: icons3Dpath + "no-mail-found.webp",
    tags: ["mail", "open", "empty", "empty mail", "post"],
    category: "objects",
  },
  {
    name: "observatory",
    path: icons3Dpath + "observatory.webp",
    tags: ["observatory", "telescope", "space", "astronaut", "stars", "sky"],
    category: "space-astronomy",
  },
  {
    name: "orange-juice",
    path: icons3Dpath + "orange-juice.webp",
    tags: [
      "orange",
      "juice",
      "orange juice",
      "drink",
      "refreshing",
      "summer",
      "cold",
    ],
    category: "food-cuisine",
  },
  {
    name: "old-wall-phone",
    path: icons3Dpath + "old-wall-phone.webp",
    tags: [
      "old wall phone",
      "wall phone",
      "old phone",
      "phone",
      "wall",
      "old",
      "history",
    ],
    category: "history-culture",
  },
  {
    name: "pagoda",
    path: icons3Dpath + "pagoda.webp",
    tags: [
      "pagoda",
      "chinese",
      "culture",
      "tradition",
      "building",
      "temple",
      "architecture",
    ],
    category: "architecture-real-estate",
  },
  {
    name: "paint-roller",
    path: icons3Dpath + "paint-roller.webp",
    tags: ["paint roller", "paint", "roller", "art", "artist", "wall"],
    category: "arts-entertainment",
  },
  {
    name: "papaya",
    path: icons3Dpath + "papaya.webp",
    tags: ["papaya", "exotic", "food", "fruit", "healthy"],
    category: "food-cuisine",
  },
  {
    name: "passport",
    path: icons3Dpath + "passport.webp",
    tags: ["passport", "travel", "fly", "flight", "airport"],
    category: "transport-travel",
  },
  {
    name: "piano",
    path: icons3Dpath + "piano.webp",
    tags: ["piano", "musical", "music", "component", "pplayer", "pianist"],
    category: "arts-entertainment",
  },
  {
    name: "picnic-basket",
    path: icons3Dpath + "picnic-basket.webp",
    tags: ["picnic basket", "picnic", "basket", "food", "healthy"],
    category: "food-cuisine",
  },
  {
    name: "podium-for-ramadan",
    path: icons3Dpath + "podium-for-ramadan.webp",
    tags: ["podium ramadan", "ramadan", "podium", "islam", "muslim"],
    category: "history-culture",
  },
  {
    name: "pretzel",
    path: icons3Dpath + "pretzel.webp",
    tags: ["pretzel", "german", "food", "salty", "bread"],
    category: "food-cuisine",
  },
  {
    name: "pumpkin",
    path: icons3Dpath + "pumpkin.webp",
    tags: ["pumpkin", "halloween", "vegetable", "harvest", "pie"],
    category: "food-cuisine",
  },
  {
    name: "red-rolling-dice",
    path: icons3Dpath + "red-rolling-dice.webp",
    tags: [
      "red rolling dice",
      "rolling dice",
      "rolling",
      "dice",
      "game",
      "luck",
    ],
    category: "sports-games",
  },
  {
    name: "robotic-arm",
    path: icons3Dpath + "robotic-arm.webp",
    tags: ["robotic arm", "robotic", "arm", "technology", "future", "ai"],
    category: "science-technology",
  },
  {
    name: "robotic-hand",
    path: icons3Dpath + "robotic-hand.webp",
    tags: ["robotic hand", "robotic", "hand", "ai", "technology"],
    category: "science-technology",
  },
  {
    name: "sakura",
    path: icons3Dpath + "sakura.webp",
    tags: ["sakura", "flower", "spring", "japanese", "cherry", "blossom"],
    category: "nature-environment",
  },
  {
    name: "saturn",
    path: icons3Dpath + "saturn.webp",
    tags: ["saturn", "planet", "space", "giant", "astronomical"],
    category: "space-astronomy",
  },
  {
    name: "save-the-earth",
    path: icons3Dpath + "save-the-earth.webp",
    tags: ["save the earth", "earth", "green", "ecology"],
    category: "nature-environment",
  },
  {
    name: "signboard",
    path: icons3Dpath + "signboard.webp",
    tags: ["signboard", "board", "sign", "decision", "future", "left", "right"],
    category: "miscellaneous",
  },
  {
    name: "solar-energy",
    path: icons3Dpath + "solar-energy.webp",
    tags: ["solar energy", "solar", "energy", "ecology", "green earth"],
    category: "nature-environment",
  },
  {
    name: "space-capsule-landed-on-moon",
    path: icons3Dpath + "space-capsule-landed-on-moon.webp",
    tags: ["space", "capsule", "moon", "landing", "astronomy"],
    category: "space-astronomy",
  },
  {
    name: "space-gun",
    path: icons3Dpath + "space-gun.webp",
    tags: ["space gun", "space", "gun", "astronomy"],
    category: "space-astronomy",
  },
  {
    name: "space-invaders",
    path: icons3Dpath + "space-invaders.webp",
    tags: ["space invaders", "space", "invaders", "arcade", "pixels"],
    category: "space-astronomy",
  },
  {
    name: "tailwind",
    path: icons3Dpath + "tailwind.webp",
    tags: ["tailwind", "programming", "coding", "css", "tailwind css"],
    category: "programming-web",
  },
  {
    name: "tennis-racket",
    path: icons3Dpath + "tennis-racket.webp",
    tags: ["tennis racket", "tennis", "racket", "game", "sports", "activity"],
    category: "sports-games",
  },
  {
    name: "tofu",
    path: icons3Dpath + "tofu.webp",
    tags: ["tofu", "food", "asian", "vegan", "vegetarian", "plant based"],
    category: "food-cuisine",
  },
  {
    name: "towel-hanger",
    path: icons3Dpath + "towel-hanger.webp",
    tags: ["towel hanger", "towel", "hanger", "dry", "smooth"],
    category: "miscellaneous",
  },
  {
    name: "tree",
    path: icons3Dpath + "tree.webp",
    tags: ["tree", "nature", "green", "forest", "ecology"],
    category: "nature-environment",
  },
  {
    name: "tulip-flower",
    path: icons3Dpath + "tulip-flower.webp",
    tags: ["tulip flower", "tulip", "flower", "nature", "spring", "bloom"],
    category: "nature-environment",
  },
  {
    name: "website-launching",
    path: icons3Dpath + "website-launching.webp",
    tags: [
      "website launching",
      "website",
      "launching",
      "web",
      "technology",
      "raket",
    ],
    category: "science-technology",
  },
  {
    name: "wind-energy",
    path: icons3Dpath + "wind-energy.webp",
    tags: ["wind energy", "wind", "energy", "green earth", "ecology", "future"],
    category: "nature-environment",
  },
  {
    name: "world-finance",
    path: icons3Dpath + "world-finance.webp",
    tags: ["world finance", "world", "finance", "money", "wealth", "economy"],
    category: "business-finance",
  },
  {
    name: "coconut-tree",
    path: icons3Dpath + "coconut-tree.webp",
    tags: ["coconut tree", "coconut", "tree", "nature", "summer", "palm"],
    category: "nature-environment",
  },
  {
    name: "essential-oil",
    path: icons3Dpath + "essential-oil.webp",
    tags: ["essential oil", "essential", "oil", "oily", "olive oil", "healthy"],
    category: "food-cuisine",
  },
  {
    name: "fencing",
    path: icons3Dpath + "fencing.webp",
    tags: [
      "fencing",
      "sport",
      "game",
      "activity",
      "championship",
      "touche",
      "swords",
    ],
    category: "sports-games",
  },
  {
    name: "history-book",
    path: icons3Dpath + "history-book.webp",
    tags: ["history book", "history", "book", "knowledge", "past", "time"],
    category: "education-academia",
  },
  {
    name: "honey-cream",
    path: icons3Dpath + "honey-cream.webp",
    tags: ["honey cream", "honey", "cream", "healthy", "beauty", "natural"],
    category: "objects",
  },
  {
    name: "honey-dipper",
    path: icons3Dpath + "honey-dipper.webp",
    tags: ["honey dipper", "honey", "dipper", "food", "healthy", "sweet"],
    category: "food-cuisine",
  },
  {
    name: "injection",
    path: icons3Dpath + "injection.webp",
    tags: ["injection", "health", "medicine", "healthcare", "hospital"],
    category: "health-medicine",
  },
  {
    name: "itza",
    path: icons3Dpath + "itza.webp",
    tags: ["itza", "ancient", "pyramids", "archaeology", "history", "culture"],
    category: "architecture-real-estate",
  },
  {
    name: "japanese-zen",
    path: icons3Dpath + "japanese-zen.webp",
    tags: [
      "japanese zen",
      "japanese",
      "zen",
      "meditation",
      "enlightenment",
      "zazen",
    ],
    category: "history-culture",
  },
  {
    name: "kabah",
    path: icons3Dpath + "kabah.webp",
    tags: ["kabah", "muslim", "islam", "pilgram", "mekkah"],
    category: "history-culture",
  },
  {
    name: "korean-banner",
    path: icons3Dpath + "korean-banner.webp",
    tags: ["korean banner", "korean", "banner", "culture", "tradition"],
    category: "history-culture",
  },
  {
    name: "korean-traditional-fan",
    path: icons3Dpath + "korean-traditional-fan.webp",
    tags: [
      "korean traditional fan",
      "traditional fan",
      "korean",
      "fan",
      "culture",
    ],
    category: "objects",
  },
  {
    name: "korean-window",
    path: icons3Dpath + "korean-window.webp",
    tags: ["korean window", "korean", "window", "culture", "tradition"],
    category: "objects",
  },
  {
    name: "life-vest",
    path: icons3Dpath + "life-vest.webp",
    tags: ["life vest", "life", "vest", "sea", "saving", "safety"],
    category: "miscellaneous",
  },
  {
    name: "lotus",
    path: icons3Dpath + "lotus.webp",
    tags: ["lotus", "flower", "blossom", "indian", "petals"],
    category: "nature-environment",
  },
  {
    name: "magician2",
    path: icons3Dpath + "magician2.webp",
    tags: ["magician", "magic", "trick", "illusion", "wand", "hat", "stab"],
    category: "arts-entertainment",
  },
  {
    name: "maha-deepam",
    path: icons3Dpath + "maha-deepam.webp",
    tags: ["maha deepam", "maha", "deepam", "temple", "tamil", "festival"],
    category: "history-culture",
  },
  {
    name: "street-lamp",
    path: icons3Dpath + "street-lamp.webp",
    tags: ["street lamp", "street", "lamp", "shining", "light"],
    category: "objects",
  },
  {
    name: "medicine",
    path: icons3Dpath + "medicine.webp",
    tags: ["medicine", "healthcare", "doctor", "pharmancy", "cure"],
    category: "health-medicine",
  },
  {
    name: "hourglass",
    path: icons3Dpath + "hourglass.webp",
    tags: ["hourglass", "time", "duration", "temporary", "hour", "glass"],
    category: "objects",
  },
  {
    name: "heart",
    path: icons3Dpath + "heart2.webp",
    tags: ["heart", "organ", "cardiovascular", "beat", "blood"],
    category: "health-medicine",
  },
  {
    name: "fingerprint-authentication",
    path: icons3Dpath + "fingerprint-authentication.webp",
    tags: [
      "fingerprint",
      "finger",
      "authentication",
      "security",
      "biometrics",
      "identity",
      "verification",
      "access",
    ],
    category: "science-technology",
  },
  {
    name: "economy-global",
    path: icons3Dpath + "economy-global.webp",
    tags: ["economy", "global", "trade", "globalization", "finance", "gpd"],
    category: "business-finance",
  },
  {
    name: "digital-camera",
    path: icons3Dpath + "digital-camera.webp",
    tags: ["digital", "camera", "picture", "photography", "image"],
    category: "arts-entertainment",
  },
  {
    name: "cctv-camera",
    path: icons3Dpath + "cctv-camera.webp",
    tags: ["cctv", "camera", "security", "privacy", "protection", "technology"],
    category: "objects",
  },
  {
    name: "air-shipping",
    path: icons3Dpath + "air-shipping.webp",
    tags: ["air", "shipping", "transport", "express", "shipment", "delivery"],
    category: "miscellaneous",
  },
  {
    name: "medicine2",
    path: icons3Dpath + "medicine2.webp",
    tags: [
      "medicine",
      "cure",
      "health",
      "medications",
      "doctor",
      "medical",
      "pharmacy",
    ],
    category: "health-medicine",
  },
  {
    name: "lock",
    path: icons3Dpath + "lock2.webp",
    tags: [
      "lock",
      "safety",
      "access",
      "security",
      "protection",
      "combination",
      "protection",
    ],
    category: "objects",
  },
  {
    name: "bank-building",
    path: icons3Dpath + "bank-building.webp",
    tags: [
      "bank",
      "finance",
      "building",
      "investment",
      "financial",
      "institution",
    ],
    category: "architecture-real-estate",
  },
  {
    name: "farmer",
    path: icons3Dpath + "farmer.webp",
    tags: ["farmer", "people", "human", "avatar", "agriculture"],
    category: "people",
  },
  {
    name: "female-accountant",
    path: icons3Dpath + "female-accountant.webp",
    tags: ["female", "people", "human", "avatar", "accounting", "profession"],
    category: "people",
  },
  {
    name: "female-call-operator",
    path: icons3Dpath + "female-call-operator.webp",
    tags: [
      "female",
      "call",
      "operator",
      "people",
      "human",
      "avatar",
      "customer-service",
      "call-center",
    ],
    category: "people",
  },
  {
    name: "female-cashier",
    path: icons3Dpath + "female-cashier.webp",
    tags: [
      "female",
      "cashier",
      "people",
      "human",
      "avatar",
      "customer-service",
    ],
    category: "people",
  },
  {
    name: "female-chef",
    path: icons3Dpath + "female-chef.webp",
    tags: ["female", "chef", "people", "human", "avatar", "business", "ceo"],
    category: "people",
  },
  {
    name: "female-cleaner",
    path: icons3Dpath + "female-cleaner.webp",
    tags: ["female", "cleaner", "people", "human", "avatar", "service", "maid"],
    category: "people",
  },
  {
    name: "female-dancer",
    path: icons3Dpath + "female-dancer.webp",
    tags: [
      "female",
      "dancer",
      "people",
      "human",
      "avatar",
      "music",
      "choreography",
    ],
    category: "people",
  },
  {
    name: "female-designer",
    path: icons3Dpath + "female-designer.webp",
    tags: [
      "female",
      "designer",
      "people",
      "human",
      "avatar",
      "fashion",
      "artist",
      "stylist",
    ],
    category: "people",
  },
  {
    name: "female-florist",
    path: icons3Dpath + "female-florist.webp",
    tags: [
      "female",
      "florist",
      "people",
      "human",
      "avatar",
      "flowers",
      "rose",
      "botanist",
    ],
    category: "people",
  },
  {
    name: "female-hairdresser",
    path: icons3Dpath + "female-hairdresser.webp",
    tags: [
      "female",
      "hairdresser",
      "people",
      "human",
      "avatar",
      "stylist",
      "hair",
      "barber",
    ],
    category: "people",
  },
  {
    name: "female-receptionist",
    path: icons3Dpath + "female-receptionist.webp",
    tags: [
      "female",
      "hostess",
      "people",
      "human",
      "avatar",
      "attendant",
      "greetress",
    ],
    category: "people",
  },
  {
    name: "gardener",
    path: icons3Dpath + "gardener.webp",
    tags: [
      "male",
      "gardener",
      "people",
      "human",
      "avatar",
      "landscaper",
      "planter",
      "agriculture",
    ],
    category: "people",
  },
  {
    name: "graduate-student",
    path: icons3Dpath + "graduate-student.webp",
    tags: [
      "male",
      "student",
      "people",
      "human",
      "avatar",
      "college",
      "graduation",
    ],
    category: "people",
  },
  {
    name: "graduated-student",
    path: icons3Dpath + "graduated-student.webp",
    tags: [
      "male",
      "student",
      "people",
      "human",
      "avatar",
      "college",
      "graduation",
    ],
    category: "people",
  },
  {
    name: "lawyer",
    path: icons3Dpath + "lawyer.webp",
    tags: [
      "male",
      "lawyer",
      "people",
      "human",
      "avatar",
      "attorney",
      "advocate",
      "jurist",
      "counsel",
    ],
    category: "people",
  },
  {
    name: "mechanic",
    path: icons3Dpath + "mechanic.webp",
    tags: [
      "male",
      "mechanic",
      "people",
      "human",
      "avatar",
      "auto",
      "engineer",
      "vehicle",
      "service",
    ],
    category: "people",
  },
  {
    name: "meteorologist",
    path: icons3Dpath + "meteorologist.webp",
    tags: [
      "female",
      "meteorologist",
      "people",
      "human",
      "avatar",
      "forecaster",
      "weather",
    ],
    category: "people",
  },
  {
    name: "model",
    path: icons3Dpath + "model.webp",
    tags: ["male", "model", "people", "human", "avatar", "fashion", "runway"],
    category: "people",
  },
  {
    name: "musician",
    path: icons3Dpath + "musician.webp",
    tags: [
      "male",
      "musician",
      "people",
      "human",
      "avatar",
      "music",
      "singer",
      "instrumentalist",
    ],
    category: "people",
  },
  {
    name: "painter",
    path: icons3Dpath + "painter.webp",
    tags: [
      "male",
      "painter",
      "people",
      "human",
      "avatar",
      "artist",
      "art",
      "creativity",
    ],
    category: "people",
  },
  {
    name: "pharmacist",
    path: icons3Dpath + "pharmacist.webp",
    tags: [
      "male",
      "pharmacist",
      "people",
      "human",
      "avatar",
      "drugstore",
      "apothecary",
      "prescription",
    ],
    category: "people",
  },
  {
    name: "photographer",
    path: icons3Dpath + "photographer.webp",
    tags: [
      "male",
      "photographer",
      "people",
      "human",
      "avatar",
      "camera",
      "photography",
    ],
    category: "people",
  },
  {
    name: "plumber",
    path: icons3Dpath + "plumber.webp",
    tags: ["male", "plumber", "people", "human", "avatar", "repair", "pipe"],
    category: "people",
  },
  {
    name: "politician",
    path: icons3Dpath + "politician.webp",
    tags: [
      "male",
      "politician",
      "people",
      "human",
      "avatar",
      "gouvernment",
      "politics",
      "law",
    ],
    category: "people",
  },
  {
    name: "salesman",
    path: icons3Dpath + "salesman.webp",
    tags: [
      "male",
      "man",
      "sales",
      "sales man",
      "people",
      "human",
      "marketing",
      "business",
    ],
    category: "people",
  },
  {
    name: "security-guard",
    path: icons3Dpath + "security-guard.webp",
    tags: [
      "male",
      "security",
      "guard",
      "human",
      "avatar",
      "protection",
      "watchman",
    ],
    category: "people",
  },
  {
    name: "teacher",
    path: icons3Dpath + "teacher.webp",
    tags: [
      "male",
      "teacher",
      "human",
      "avatar",
      "wise",
      "teaching",
      "lecture",
      "professor",
    ],
    category: "people",
  },
  {
    name: "electrician",
    path: icons3Dpath + "electrician.webp",
    tags: [
      "electrician",
      "male",
      "people",
      "human",
      "electricy",
      "wiring",
      "technician",
    ],
    category: "people",
  },
  {
    name: "driver",
    path: icons3Dpath + "driver.webp",
    tags: ["male", "people", "human", "avatar", "car", "taxi", "driver"],
    category: "people",
  },
  {
    name: "dentist",
    path: icons3Dpath + "dentist.webp",
    tags: ["male", "people", "human", "avatar", "dental", "hygiene", "oral"],
    category: "people",
  },
  {
    name: "customer-supporter",
    path: icons3Dpath + "customer-supporter.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "customer supporter",
      "supporter",
      "assistance",
    ],
    category: "people",
  },
  {
    name: "carpenter",
    path: icons3Dpath + "carpenter.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "carpenter",
      "woodwork",
      "craftsman",
    ],
    category: "people",
  },
  {
    name: "butcher-man",
    path: icons3Dpath + "butcher-man.webp",
    tags: ["male", "people", "human", "avatar", "butcher", "meat", "butchery"],
    category: "people",
  },
  {
    name: "baker",
    path: icons3Dpath + "baker.webp",
    tags: ["male", "people", "human", "avatar", "baker", "baking", "pastery"],
    category: "people",
  },
  {
    name: "actress",
    path: icons3Dpath + "actress.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "actress",
      "role",
      "cast",
      "cinema",
    ],
    category: "people",
  },
  {
    name: "actor",
    path: icons3Dpath + "actor.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "actress",
      "role",
      "cast",
      "cinema",
    ],
    category: "people",
  },
  {
    name: "businesswoman",
    path: icons3Dpath + "businesswoman.webp",
    tags: ["business", "female", "woman", "people", "human", "ceo"],
    category: "people",
  },
  {
    name: "architect",
    path: icons3Dpath + "architect.webp",
    tags: ["male", "people", "human", "buildings", "creativity"],
    category: "people",
  },
  {
    name: "administrator",
    path: icons3Dpath + "administrator.webp",
    tags: ["male", "people", "human", "director", "authority"],
    category: "people",
  },
  {
    name: "artist",
    path: icons3Dpath + "artist.webp",
    tags: [
      "male",
      "people",
      "human",
      "art",
      "artist",
      "creativity",
      "painting",
    ],
    category: "people",
  },
  {
    name: "male-construction-worker",
    path: icons3Dpath + "male-construction-worker.webp",
    tags: [
      "male",
      "people",
      "human",
      "worker",
      "construction",
      "builder",
      "craftsmanship",
    ],
    category: "people",
  },
  {
    name: "nanny",
    path: icons3Dpath + "nanny.webp",
    tags: ["female", "people", "human", "nanny", "babysitter", "caregiver"],
    category: "people",
  },
  {
    name: "judge",
    path: icons3Dpath + "judge.webp",
    tags: [
      "male",
      "people",
      "human",
      "law",
      "avatar",
      "judge",
      "court",
      "lawsuit",
    ],
    category: "people",
  },
  {
    name: "programmer",
    path: icons3Dpath + "programmer.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "programmer",
      "coding",
      "technology",
    ],
    category: "people",
  },
  {
    name: "saleswoman",
    path: icons3Dpath + "saleswoman.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "sales",
      "woman",
      "business",
      "marketing",
    ],
    category: "people",
  },
  {
    name: "researcher",
    path: icons3Dpath + "researcher.webp",
    tags: ["male", "people", "human", "avatar", "researcher", "laboratory"],
    category: "people",
  },
  {
    name: "flight-attendant",
    path: icons3Dpath + "flight-attendant.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "flight attendant",
      "flight",
      "aeropot",
      "attendant",
    ],
    category: "people",
  },
  {
    name: "biologist",
    path: icons3Dpath + "biologist.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "biologist",
      "biology",
      "researcher",
      "laboratory",
    ],
    category: "people",
  },
  {
    name: "farmer-woman",
    path: icons3Dpath + "farmer-woman.webp",
    tags: ["female", "people", "human", "avatar", "agriculture", "farmer"],
    category: "people",
  },
  {
    name: "engineer",
    path: icons3Dpath + "engineer.webp",
    tags: ["male", "people", "human", "avatar", "engineer", "repairature"],
    category: "people",
  },
  {
    name: "doctor-women",
    path: icons3Dpath + "doctor-women.webp",
    tags: [
      "female",
      "women",
      "people",
      "human",
      "avatar",
      "doctor",
      "healthcare",
      "hospital",
    ],
    category: "people",
  },
  {
    name: "doctor-man",
    path: icons3Dpath + "doctor-man.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "doctor",
      "healthcare",
      "hospital",
      "man",
    ],
    category: "people",
  },
  {
    name: "detective",
    path: icons3Dpath + "detective.webp",
    tags: ["male", "people", "human", "avatar", "detective", "spy"],
    category: "people",
  },
  {
    name: "croupier-man",
    path: icons3Dpath + "croupier-man.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "croupier",
      "man",
      "gambling",
      "casino",
      "poker",
    ],
    category: "people",
  },
  {
    name: "courier-boy",
    path: icons3Dpath + "courier-boy.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "courier",
      "boy",
      "deliveryman",
      "service",
    ],
    category: "people",
  },
  {
    name: "content-writer",
    path: icons3Dpath + "content-writer.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "content",
      "writer",
      "blogger",
    ],
    category: "people",
  },
  {
    name: "concierge",
    path: icons3Dpath + "concierge.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "hospitality",
      "concierge",
      "hospitality",
      "helper",
    ],
    category: "people",
  },
  {
    name: "cock-man",
    path: icons3Dpath + "cock-man.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "cockman",
      "cooking",
      "restaurant",
      "cuisine",
      "food",
    ],
    category: "people",
  },
  {
    name: "chef",
    path: icons3Dpath + "chef.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "restaurant",
      "cooking",
      "cuisine",
      "food",
    ],
    category: "people",
  },
  {
    name: "cashier-man",
    path: icons3Dpath + "cashier-man.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "cashier",
      "man",
      "sales",
      "payment",
    ],
    category: "people",
  },
  {
    name: "captain",
    path: icons3Dpath + "captain.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "captain",
      "boat",
      "commander",
      "sea",
    ],
    category: "people",
  },
  {
    name: "call-operator",
    path: icons3Dpath + "call-operator.webp",
    tags: ["male", "people", "human", "avatar", "call", "operator", "service"],
    category: "people",
  },
  {
    name: "businessman",
    path: icons3Dpath + "businessman.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "businessman",
      "business",
      "ceo",
      "head",
    ],
    category: "people",
  },
  {
    name: "businessman2",
    path: icons3Dpath + "businessman2.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "businessman",
      "business",
      "ceo",
      "head",
    ],
    category: "people",
  },
  {
    name: "builder",
    path: icons3Dpath + "builder.webp",
    tags: ["male", "people", "human", "avatar", "builder", "craftsman"],
    category: "people",
  },
  {
    name: "builder-woman",
    path: icons3Dpath + "builder-woman.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "builder",
      "womam",
      "craftswoman",
    ],
    category: "people",
  },
  {
    name: "astronaut",
    path: icons3Dpath + "astronout.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "astronout",
      "space",
      "physics",
      "astronomy",
      "earth",
      "galaxis",
      "spaceship",
    ],
    category: "people",
  },
  {
    name: "astronaut",
    path: icons3Dpath + "astronaut.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "astronaut",
      "space",
      "physics",
      "astronomy",
      "earth",
      "galaxis",
      "spaceship",
    ],
    category: "people",
  },
  {
    name: "soldier",
    path: icons3Dpath + "soldier.webp",
    tags: ["male", "people", "human", "avatar", "nave", "soldier", "loyalty"],
    category: "people",
  },
  {
    name: "singer",
    path: icons3Dpath + "singer.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "singer",
      "stage",
      "music",
      "vocal",
    ],
    category: "people",
  },
  {
    name: "showman",
    path: icons3Dpath + "showman.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "showman",
      "show",
      "entertainment",
      "showbiz",
    ],
    category: "people",
  },
  {
    name: "shop-assistant",
    path: icons3Dpath + "shop-assistant.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "shop",
      "assistant",
      "sell",
      "sales",
      "cashier",
    ],
    category: "people",
  },
  {
    name: "sheriff2",
    path: icons3Dpath + "sheriff2.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "sheriff",
      "lawman",
      "officer",
      "policy",
    ],
    category: "people",
  },
  {
    name: "scuba-diver",
    path: icons3Dpath + "scuba-diver.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "scuba",
      "diver",
      "sea",
      "water sport",
    ],
    category: "people",
  },
  {
    name: "post-man",
    path: icons3Dpath + "post-man.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "post",
      "man",
      "delivery",
      "shipping",
    ],
    category: "people",
  },
  {
    name: "policeman",
    path: icons3Dpath + "policeman.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "policeman",
      "police",
      "safety",
      "executives",
    ],
    category: "people",
  },
  {
    name: "pilot",
    path: icons3Dpath + "pilot.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "pilot",
      "fly",
      "aviator",
      "aircraft",
    ],
    category: "people",
  },
  {
    name: "nurse",
    path: icons3Dpath + "nurse.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "nurse",
      "caring",
      "healthcare",
      "nursery",
      "hospital",
    ],
    category: "people",
  },
  {
    name: "navy-officer",
    path: icons3Dpath + "navy-officer.webp",
    tags: ["male", "people", "human", "avatar", "navy", "officer", "military"],
    category: "people",
  },
  {
    name: "motorcyclist",
    path: icons3Dpath + "motorcyclist.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "motorcyclist",
      "motorcycle",
      "biker",
      "racing",
    ],
    category: "people",
  },
  {
    name: "miner",
    path: icons3Dpath + "miner.webp",
    tags: ["male", "people", "human", "avatar", "miner", "gigging", "coal"],
    category: "people",
  },
  {
    name: "manager",
    path: icons3Dpath + "manager.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "manager",
      "supervisor",
      "management",
    ],
    category: "people",
  },
  {
    name: "male-speaker",
    path: icons3Dpath + "male-speaker.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "male",
      "speaker",
      "public speeking",
      "male speaker",
    ],
    category: "people",
  },
  {
    name: "male-scientist",
    path: icons3Dpath + "male-scientist.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "male scientist",
      "male",
      "scientist",
      "science",
      "physics",
    ],
    category: "people",
  },
  {
    name: "magician",
    path: icons3Dpath + "magician.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "magician",
      "magic",
      "game",
      "entertainment",
    ],
    category: "people",
  },
  {
    name: "loader",
    path: icons3Dpath + "loader.webp",
    tags: ["male", "people", "human", "avatar", "loader", "operator"],
    category: "people",
  },
  {
    name: "lab-technician",
    path: icons3Dpath + "lab-technician.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "lab-technician",
      "lab",
      "technician",
    ],
    category: "people",
  },
  {
    name: "journalist",
    path: icons3Dpath + "journalist.webp",
    tags: ["male", "people", "human", "avatar", "journalist", "media", "news"],
    category: "people",
  },
  {
    name: "interpreter",
    path: icons3Dpath + "interpreter.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "interpreter",
      "translator",
      "languages",
      "multilingual",
    ],
    category: "people",
  },
  {
    name: "girl",
    path: icons3Dpath + "girl.webp",
    tags: ["female", "people", "human", "avatar", "girl"],
    category: "people",
  },
  {
    name: "gamer",
    path: icons3Dpath + "gamer.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "gaming",
      "gamer",
      "games",
      "online",
    ],
    category: "people",
  },
  {
    name: "waiter",
    path: icons3Dpath + "waiter.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "waiter",
      "server",
      "waitstaff",
    ],
    category: "people",
  },
  {
    name: "veterinarian",
    path: icons3Dpath + "veterinarian.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "veterinarian",
      "animals",
      "healthcare",
    ],
    category: "people",
  },
  {
    name: "travel-guide",
    path: icons3Dpath + "travel-guide.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "travel guide",
      "travel",
      "guide",
      "tourism",
    ],
    category: "people",
  },
  {
    name: "travel-agent",
    path: icons3Dpath + "travel-agent.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "travel agent",
      "trave",
      "agency",
      "agent",
      "tourism",
    ],
    category: "people",
  },
  {
    name: "thief",
    path: icons3Dpath + "thief.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "thief",
      "crime",
      "criminal",
      "bandit",
      "robbery",
    ],
    category: "people",
  },
  {
    name: "thief-man",
    path: icons3Dpath + "thief-man.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "thief",
      "crime",
      "criminal",
      "bandit",
      "robbery",
    ],
    category: "people",
  },
  {
    name: "technical-support",
    path: icons3Dpath + "technical-support.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "technical support",
      "technical",
      "support",
      "technology",
    ],
    category: "people",
  },
  {
    name: "teacher2",
    path: icons3Dpath + "teacher2.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "teacher",
      "teaching",
      "education",
      "lessons",
    ],
    category: "people",
  },
  {
    name: "taxi-driver",
    path: icons3Dpath + "taxi-driver.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "taxi driver",
      "taxi",
      "driver",
      "car",
    ],
    category: "people",
  },
  {
    name: "swat",
    path: icons3Dpath + "swat.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "swat",
      "navy",
      "weapons",
      "sniper",
    ],
    category: "people",
  },
  {
    name: "surgeon",
    path: icons3Dpath + "surgeon.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "surgeon",
      "healthcare",
      "hospital",
    ],
    category: "people",
  },
  {
    name: "student",
    path: icons3Dpath + "student.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "student",
      "learning",
      "education",
      "knowledge",
      "study",
    ],
    category: "people",
  },
  {
    name: "steward",
    path: icons3Dpath + "steward.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "steward",
      "service",
      "airline",
      "cabin",
    ],
    category: "people",
  },
  {
    name: "soldier-man",
    path: icons3Dpath + "soldier-man.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "soldier man",
      "soldier",
      "man",
    ],
    category: "people",
  },
  {
    name: "waitress",
    path: icons3Dpath + "waitress.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "waitress",
      "server",
      "waitstaff",
    ],
    category: "people",
  },
  {
    name: "welder",
    path: icons3Dpath + "welder.webp",
    tags: ["male", "people", "human", "avatar", "metalworker", "fabricator"],
    category: "people",
  },
  {
    name: "barber",
    path: icons3Dpath + "barber.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "barber",
      "haircut",
      "hairsalon",
    ],
    category: "people",
  },
  {
    name: "firefighter",
    path: icons3Dpath + "firefighter.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "firefighter",
      "rescuer",
      "fireman",
    ],
    category: "people",
  },
  {
    name: "female-sales-assistant",
    path: icons3Dpath + "female-sales-assistant.webp",
    tags: [
      "female",
      "people",
      "human",
      "avatar",
      "female sales assistant",
      "sales",
      "assistant",
      "marketing",
    ],
    category: "people",
  },
  {
    name: "dj",
    path: icons3Dpath + "dj.webp",
    tags: [
      "male",
      "people",
      "human",
      "avatar",
      "dj",
      "music",
      "party",
      "disco",
    ],
    category: "people",
  },
];
